name: eyes_tracker
description: "A new Flutter project."
publish_to: 'none' 
version: 1.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  eyedid_flutter: ^1.0.0-beta4

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  connectivity_plus: ^6.1.5
  internet_connection_checker: ^3.0.1
  showcaseview:
    git:
        url: https://github.com/SimformSolutionsPvtLtd/flutter_showcaseview.git
        ref: 2cf17b339fa19aaf6cf901f8072c4010f313f81b
  shared_preferences: ^2.5.3
  eye_tracking_plus: ^0.1.1
  web: ^1.1.1
  #internet_connection_checker_plus: ^2.7.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
